DELETE FROM `product_composition`;
DELETE FROM `dish_product`;
DELETE FROM `day_timed_dish`;
DELETE FROM `user_day`;
DELETE FROM `product`;
DELETE FROM `composition`;
DELETE FROM `timed_dish`;
DELETE FROM `dish`;
DELETE FROM `day`;