ALTER TABLE `diagnostic` AUTO_INCREMENT = 1;
ALTER TABLE `diet` AUTO_INCREMENT = 1;
ALTER TABLE `privilege` AUTO_INCREMENT = 1;
ALTER TABLE `role` AUTO_INCREMENT = 1;
ALTER TABLE `user` AUTO_INCREMENT = 1;